import { SubtitleTrack, SubtitleCue, YouTubePlayerState } from '@/types';

export class YouTubeSubtitleDetector {
  private observer: MutationObserver | null = null;
  private playerElement: Element | null = null;
  private subtitleTracks: SubtitleTrack[] = [];
  private currentTrack: SubtitleTrack | null = null;
  private onSubtitleDetected?: (track: SubtitleTrack) => void;
  private onPlayerStateChange?: (state: YouTubePlayerState) => void;

  constructor() {
    this.initialize();
  }

  private initialize() {
    // Wait for YouTube player to be ready
    this.waitForYouTubePlayer();
  }

  private waitForYouTubePlayer() {
    const checkPlayer = () => {
      const player = document.querySelector('#movie_player') || 
                    document.querySelector('.html5-video-player') ||
                    document.querySelector('video');

      if (player) {
        this.playerElement = player;
        this.setupPlayerListeners();
        this.detectSubtitles();
        this.startObservation();
      } else {
        setTimeout(checkPlayer, 100);
      }
    };

    checkPlayer();
  }

  private setupPlayerListeners() {
    const video = document.querySelector('video');
    if (!video) return;

    // Monitor video time updates for subtitle synchronization
    video.addEventListener('timeupdate', () => {
      this.updateCurrentSubtitles(video.currentTime);
    });

    // Monitor video load events
    video.addEventListener('loadedmetadata', () => {
      this.detectSubtitles();
    });

    // Monitor subtitle track changes
    video.addEventListener('loadeddata', () => {
      this.detectSubtitles();
    });
  }

  private startObservation() {
    if (!this.playerElement) return;

    // Observe DOM changes for subtitle elements
    this.observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === 'childList') {
          mutation.addedNodes.forEach((node) => {
            if (node.nodeType === Node.ELEMENT_NODE) {
              const element = node as Element;
              if (element.classList?.contains('caption-window') ||
                  element.classList?.contains('ytp-caption-segment') ||
                  element.tagName === 'TRACK') {
                this.detectSubtitles();
              }
            }
          });
        }
      });
    });

    this.observer.observe(this.playerElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['aria-label', 'data-caption']
    });
  }

  private detectSubtitles() {
    this.subtitleTracks = [];
    
    // Method 1: Check for native subtitle tracks
    this.detectNativeTracks();
    
    // Method 2: Parse YouTube's caption data
    this.parseYouTubeCaptionData();
    
    // Method 3: Extract from DOM elements
    this.extractFromDOM();

    if (this.subtitleTracks.length > 0) {
      this.notifySubtitleDetection();
    }
  }

  private detectNativeTracks() {
    const video = document.querySelector('video');
    if (!video) return;

    const tracks = video.textTracks;
    for (let i = 0; i < tracks.length; i++) {
      const track = tracks[i];
      if (track.kind === 'subtitles' || track.kind === 'captions') {
        const subtitleTrack = this.parseTextTrack(track);
        if (subtitleTrack) {
          this.subtitleTracks.push(subtitleTrack);
        }
      }
    }
  }

  private parseTextTrack(track: TextTrack): SubtitleTrack | null {
    const cues: SubtitleCue[] = [];
    
    if (!track.cues) return null;
    
    for (let i = 0; i < track.cues.length; i++) {
      const cue = track.cues[i] as VTTCue;
      cues.push({
        id: `cue-${i}`,
        startTime: cue.startTime,
        endTime: cue.endTime,
        text: cue.text,
        originalText: cue.text
      });
    }

    return {
      language: track.language || 'unknown',
      kind: track.kind as 'subtitles' | 'captions' | 'descriptions',
      label: track.label || `${track.language} - ${track.kind}`,
      isAutoGenerated: track.label?.toLowerCase().includes('auto') || false,
      cues
    };
  }

  private parseYouTubeCaptionData() {
    // Try to extract caption data from YouTube's internal data
    try {
      const captionData = this.extractYouTubeCaptionData();
      if (captionData) {
        captionData.forEach((data: any) => {
          const track: SubtitleTrack = {
            language: data.languageCode || 'en',
            kind: data.kind || 'subtitles',
            label: data.name || `${data.languageCode} subtitles`,
            isAutoGenerated: data.isAutoGenerated || false,
            cues: data.cues || []
          };
          this.subtitleTracks.push(track);
        });
      }
    } catch (error) {
      console.warn('Failed to parse YouTube caption data:', error);
    }
  }

  private extractYouTubeCaptionData(): any[] | null {
    // Look for caption data in YouTube's page data
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const content = script.textContent;
      if (content && content.includes('captionTracks')) {
        try {
          // Extract JSON data from script content
          const match = content.match(/\"captionTracks\":\s*(\[.*?\])/);
          if (match) {
            return JSON.parse(match[1]);
          }
        } catch (error) {
          // Continue to next script
        }
      }
    }
    return null;
  }

  private extractFromDOM() {
    // Extract subtitles from DOM elements (real-time)
    const captionElements = document.querySelectorAll('.ytp-caption-segment, .caption-window');
    
    if (captionElements.length > 0) {
      const cues: SubtitleCue[] = [];
      const video = document.querySelector('video');
      const currentTime = video?.currentTime || 0;

      captionElements.forEach((element, index) => {
        const text = element.textContent?.trim();
        if (text) {
          cues.push({
            id: `dom-cue-${index}`,
            startTime: currentTime,
            endTime: currentTime + 5, // Default duration
            text,
            originalText: text
          });
        }
      });

      if (cues.length > 0) {
        this.subtitleTracks.push({
          language: 'en', // Default language
          kind: 'captions',
          label: 'DOM Extracted Captions',
          isAutoGenerated: true,
          cues
        });
      }
    }
  }

  private updateCurrentSubtitles(currentTime: number) {
    if (!this.currentTrack) return;

    // Find active subtitle at current time
    const activeCues = this.currentTrack.cues.filter(
      cue => currentTime >= cue.startTime && currentTime <= cue.endTime
    );

    if (activeCues.length > 0) {
      // Update subtitle overlay with active cues
      this.onSubtitleDetected?.({
        ...this.currentTrack,
        cues: activeCues
      });
    }
  }

  private notifySubtitleDetection() {
    if (this.subtitleTracks.length > 0) {
      // Set the first available track as current
      this.currentTrack = this.subtitleTracks[0];
      this.onSubtitleDetected?.(this.currentTrack);
    }
  }

  public setSubtitleDetectionCallback(callback: (track: SubtitleTrack) => void) {
    this.onSubtitleDetected = callback;
  }

  public setPlayerStateCallback(callback: (state: YouTubePlayerState) => void) {
    this.onPlayerStateChange = callback;
  }

  public getAvailableTracks(): SubtitleTrack[] {
    return this.subtitleTracks;
  }

  public selectTrack(language: string, kind?: string): boolean {
    const track = this.subtitleTracks.find(t => 
      t.language === language && 
      (!kind || t.kind === kind)
    );

    if (track) {
      this.currentTrack = track;
      this.onSubtitleDetected?.(track);
      return true;
    }
    return false;
  }

  public getCurrentTrack(): SubtitleTrack | null {
    return this.currentTrack;
  }

  public getPlayerState(): YouTubePlayerState | null {
    const video = document.querySelector('video');
    if (!video) return null;

    const urlParams = new URLSearchParams(window.location.search);
    const videoId = urlParams.get('v');

    return {
      videoId: videoId || '',
      currentTime: video.currentTime,
      duration: video.duration,
      isPaused: video.paused,
      playbackRate: video.playbackRate,
      volume: video.volume
    };
  }

  public destroy() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
    this.playerElement = null;
    this.subtitleTracks = [];
    this.currentTrack = null;
  }
}
