// Core types for the Live AI Subtitle Translator extension

export interface SubtitleCue {
  id: string;
  startTime: number;
  endTime: number;
  text: string;
  originalText?: string;
  translatedText?: string;
  confidence?: number;
  speaker?: string;
}

export interface SubtitleTrack {
  language: string;
  kind: 'subtitles' | 'captions' | 'descriptions';
  label: string;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
}

export interface TranslationSettings {
  sourceLanguage: string;
  targetLanguage: string;
  translationProvider: 'libretranslate' | 'openrouter' | 'google';
  apiKey?: string;
  endpoint?: string;
}

export interface SubtitleStyle {
  fontSize: number;
  fontFamily: string;
  color: string;
  backgroundColor: string;
  opacity: number;
  position: 'bottom' | 'top' | 'center';
  maxWidth: number;
  lineHeight: number;
  textShadow: string;
  backdropBlur: number;
}

export interface AISettings {
  whisperModel: 'tiny' | 'base' | 'small' | 'medium' | 'large';
  enableLiveTranscription: boolean;
  autoQualityMode: boolean;
  silenceThreshold: number;
  chunkDuration: number;
}

export interface ExtensionSettings {
  enabled: boolean;
  translation: TranslationSettings;
  subtitleStyle: SubtitleStyle;
  ai: AISettings;
  dualSubtitleMode: boolean;
  hotkeys: Record<string, string>;
  autoDetectLanguage: boolean;
}

export interface AudioChunk {
  data: Float32Array;
  sampleRate: number;
  timestamp: number;
}

export interface TranscriptionResult {
  text: string;
  confidence: number;
  timestamp: number;
  duration: number;
  speaker?: string;
}

export interface TranslationResult {
  originalText: string;
  translatedText: string;
  sourceLanguage: string;
  targetLanguage: string;
  confidence: number;
  processingTime: number;
}

export interface YouTubePlayerState {
  videoId: string;
  currentTime: number;
  duration: number;
  isPaused: boolean;
  playbackRate: number;
  volume: number;
}

export interface SubtitleOverlayState {
  isVisible: boolean;
  position: { x: number; y: number };
  size: { width: number; height: number };
  isDragging: boolean;
  isResizing: boolean;
}

export interface ExportFormat {
  format: 'srt' | 'txt' | 'vtt';
  includeTranslation: boolean;
  includeTimestamps: boolean;
}

// API Response types
export interface LibreTranslateResponse {
  translatedText: string;
  confidence?: number;
}

export interface WhisperResponse {
  text: string;
  segments?: Array<{
    start: number;
    end: number;
    text: string;
    confidence: number;
  }>;
}

// Message types for extension communication
export type ExtensionMessage = 
  | { type: 'GET_SETTINGS' }
  | { type: 'UPDATE_SETTINGS'; payload: Partial<ExtensionSettings> }
  | { type: 'START_TRANSCRIPTION' }
  | { type: 'STOP_TRANSCRIPTION' }
  | { type: 'TRANSCRIPTION_RESULT'; payload: TranscriptionResult }
  | { type: 'TRANSLATE_TEXT'; payload: { text: string; from: string; to: string } }
  | { type: 'TRANSLATION_RESULT'; payload: TranslationResult }
  | { type: 'SUBTITLE_DETECTED'; payload: SubtitleTrack }
  | { type: 'UPDATE_SUBTITLE_OVERLAY'; payload: Partial<SubtitleOverlayState> }
  | { type: 'EXPORT_SUBTITLES'; payload: ExportFormat }
  | { type: 'YOUTUBE_PLAYER_STATE'; payload: YouTubePlayerState };

// Language codes
export const SUPPORTED_LANGUAGES = {
  en: 'English',
  ne: 'Nepali',
  hi: 'Hindi',
  ja: 'Japanese',
  ko: 'Korean',
  zh: 'Chinese',
  ar: 'Arabic',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  ru: 'Russian',
  pt: 'Portuguese',
  it: 'Italian',
  nl: 'Dutch',
  sv: 'Swedish',
  da: 'Danish',
  no: 'Norwegian',
  fi: 'Finnish',
  pl: 'Polish',
  tr: 'Turkish'
} as const;

export type LanguageCode = keyof typeof SUPPORTED_LANGUAGES;

// Default settings
export const DEFAULT_SETTINGS: ExtensionSettings = {
  enabled: true,
  translation: {
    sourceLanguage: 'auto',
    targetLanguage: 'en',
    translationProvider: 'libretranslate'
  },
  subtitleStyle: {
    fontSize: 16,
    fontFamily: 'Arial, sans-serif',
    color: '#FFFFFF',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    opacity: 0.9,
    position: 'bottom',
    maxWidth: 80,
    lineHeight: 1.4,
    textShadow: '2px 2px 4px rgba(0, 0, 0, 0.8)',
    backdropBlur: 4
  },
  ai: {
    whisperModel: 'base',
    enableLiveTranscription: true,
    autoQualityMode: true,
    silenceThreshold: 0.1,
    chunkDuration: 2000
  },
  dualSubtitleMode: false,
  hotkeys: {
    toggle: 'Alt+S',
    switchLanguage: 'Alt+L',
    moveUp: 'Alt+Up',
    moveDown: 'Alt+Down',
    increaseSize: 'Alt+Plus',
    decreaseSize: 'Alt+Minus'
  },
  autoDetectLanguage: true
};
